/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    1: typeof import('./src/components/1.vue')['default']
    Cloud: typeof import('./src/components/cloud.vue')['default']
    Danzi: typeof import('./src/components/fenxi/danzi.vue')['default']
    Datasource: typeof import('./src/components/datasource.vue')['default']
    Dropdown: typeof import('./src/components/dropdown.vue')['default']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Fenduan: typeof import('./src/components/gailan/fenduan.vue')['default']
    Guangyun: typeof import('./src/components/yunbu/guangyun.vue')['default']
    Introduction: typeof import('./src/components/introduction.vue')['default']
    Nav: typeof import('./src/components/nav.vue')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
    Quanmao: typeof import('./src/components/gailan/quanmao.vue')['default']
    Research: typeof import('./src/components/research.vue')['default']
    Riverflow: typeof import('./src/components/riverflow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shijing: typeof import('./src/components/yunbu/shijing.vue')['default']
    Show: typeof import('./src/components/show.vue')['default']
    Transition: typeof import('./src/components/transition.vue')['default']
    Zhengti: typeof import('./src/components/fenxi/zhengti.vue')['default']
    Zhongyuan: typeof import('./src/components/yunbu/zhongyuan.vue')['default']
  }
}
