/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Cloud: typeof import('./src/components/cloud.vue')['default']
    Danzi: typeof import('./src/components/fenxi/danzi.vue')['default']
    Datasource: typeof import('./src/components/datasource.vue')['default']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Fenxi: typeof import('./src/components/fenxi/fenxi.vue')['default']
    Flow: typeof import('./src/components/fenxi/flow.vue')['default']
    Guangyun: typeof import('./src/components/quanlan/guangyun.vue')['default']
    Gyyunbu: typeof import('./src/components/yunbu/gyyunbu.vue')['default']
    Introduction: typeof import('./src/components/introduction.vue')['default']
    Juanzhou: typeof import('./src/components/fenxi/juanzhou.vue')['default']
    Nav1: typeof import('./src/components/nav/nav1.vue')['default']
    Nav2: typeof import('./src/components/nav/nav2.vue')['default']
    Nav3: typeof import('./src/components/nav/nav3.vue')['default']
    Nav4: typeof import('./src/components/nav/nav4.vue')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
    Navbar1: typeof import('./src/components/nav/navbar1.vue')['default']
    Navbar2: typeof import('./src/components/nav/navbar2.vue')['default']
    Navbar3: typeof import('./src/components/nav/navbar3.vue')['default']
    NavbarDicard: typeof import('./src/components/navbar-dicard.vue')['default']
    Quanlan: typeof import('./src/components/quanlan/quanlan.vue')['default']
    Research: typeof import('./src/components/research.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shijing: typeof import('./src/components/quanlan/shijing.vue')['default']
    ShijingDiscard: typeof import('./src/components/quanlan/shijing-discard.vue')['default']
    Shouye: typeof import('./src/components/shouye/shouye.vue')['default']
    Show: typeof import('./src/components/show.vue')['default']
    SjL3: typeof import('./src/components/yunbu/sjL3.vue')['default']
    Sjyunbu: typeof import('./src/components/yunbu/sjyunbu.vue')['default']
    Test: typeof import('./src/components/test.vue')['default']
    Test2: typeof import('./src/components/test2.vue')['default']
    Test3: typeof import('./src/components/test3.vue')['default']
    Yunbu: typeof import('./src/components/yunbu/yunbu.vue')['default']
    Yunbu2: typeof import('./src/components/yunbu/yunbu2.vue')['default']
    Yunbu3: typeof import('./src/components/yunbu/yunbu3.vue')['default']
    YunbuDiscard: typeof import('./src/components/yunbu/yunbu-discard.vue')['default']
    Zhengti: typeof import('./src/components/fenxi/zhengti.vue')['default']
    Zhongyuan: typeof import('./src/components/quanlan/zhongyuan.vue')['default']
    Zyyunbu: typeof import('./src/components/yunbu/zyyunbu.vue')['default']
  }
}
